# Generated by Django 4.2.7 on 2025-03-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
