# Generated by Django 4.2.7 on 2025-03-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mark',
            new_name='subject',
        ),
    ]
