# Generated by Django 4.2.7 on 2025-03-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_rename_mark_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
