# Generated by Django 4.2.7 on 2025-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0002_profile2model_remove_profilemodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='City',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
