# Generated by Django 4.2.7 on 2025-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0004_remove_profilemodel_city_profile2model_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile2model',
            name='City',
            field=models.CharField(max_length=30),
        ),
    ]
