# Generated by Django 4.2.7 on 2025-03-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0005_alter_profile2model_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile2model',
            name='City',
        ),
    ]
