# Generated by Django 4.2.7 on 2025-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0006_remove_profile2model_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile2model',
            name='City',
            field=models.CharField(default=233123312, max_length=30),
            preserve_default=False,
        ),
    ]
