# Generated by Django 4.2.7 on 2025-03-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0008_rename_city_profile2model_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile2model',
            old_name='city',
            new_name='City',
        ),
    ]
