# Generated by Django 4.2.7 on 2025-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0010_remove_profile2model_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload', models.ImageField(upload_to='')),
            ],
        ),
    ]
