# Generated by Django 4.2.7 on 2025-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0011_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filemodel',
        ),
        migrations.AddField(
            model_name='profile2model',
            name='Upload',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
