# Generated by Django 4.2.7 on 2025-03-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_3', '0012_delete_filemodel_profile2model_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile2model',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile2model',
            name='Upload',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
