# Generated by Django 4.2.7 on 2025-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0013_profile2model_user_alter_profile2model_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile2model',
            name='Upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
