# Generated by Django 4.2.7 on 2025-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0014_alter_profile2model_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile2model',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile2model',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile2model',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile2model',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile2model',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='profile2model',
            name='Upload',
        ),
        migrations.AddField(
            model_name='profile2model',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/'),
        ),
    ]
