# Generated by Django 5.0 on 2025-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0015_rename_address_profile2model_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile2model',
            name='user',
        ),
    ]
